docs:
    script:
        - make Docs
        - cp -r doc/html /var/www/docs/wormhole
    tags:
        - docs

ubuntu16.04:
    script:
        - make -j
    artifacts:
        paths:
        - build/lib
        - build/bin
        - build/examples
        - build/certs
        - doc
        expire_in: 4 weeks
    tags:
        - ubuntu16.04

before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
    - git submodule sync --recursive || true
    - git submodule update --recursive || true
        
clean:
    script:
        - make clean
    when: on_failure
