docs:
    script:
        - make Docs
        - cp -r doc/html /var/www/docs/wormhole

compilation:
    script:
        - make -j
    artifacts:
        paths:
        - build/lib
        - doc
        - build/bin
        #- certs

before_script:
    - killall -9 testSendAsync testRecvAsync testRecvSSL testSendSSL testRecvAsyncSSL testSendAsyncSSL || true
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
    - git submodule update --recursive || true
        
clean:
    script:
        - make clean
        - killall -9 testSendAsync testRecvAsync testRecvSSL testSendSSL testRecvAsyncSSL testSendAsyncSSL || true
    when: on_failure
