compilation:
    script:
        - make

docs:
    script:
        - make Docs
        - cp -r doc/html /var/www/docs/wormhole

test_commonh_test_async:
    script:
        - make bin/testSendAsync bin/testRecvAsync
        - cd bin
        - ./testRecvAsync &
        - ./testSendAsync || (killall -9 testRecvAsync ; false)
        
test_commonh_test_SSL:
    script:
        - make bin/testSendSSL bin/testRecvSSL
        - cd bin
        - ./testRecvSSL &
        - ./testSendSSL || (killall -9 testRecvSSL ; false)
        
test_commonh_test_AsyncSSL:
    script:
        - make bin/testSendAsyncSSL bin/testRecvAsyncSSL
        - cd bin
        - ./testRecvAsyncSSL &
        - ./testSendAsyncSSL || (killall -9 testRecvAsyncSSL ; false)
        
clean:
    script:
        - make clean
        - killall -9 testSendAsync testRecvAsync testRecvSSL testSendSSL testRecvAsyncSSL testSendAsyncSSL || true
    when: on_failure
