/* DO NOT EDIT THIS FILE - it is machine generated */
#include "es_hpcn_wormhole_Worm.h"
/* Header for class es_hpcn_wormhole_Worm */

#ifndef _Included_es_hpcn_wormhole_Worm
#define _Included_es_hpcn_wormhole_Worm
#ifdef __cplusplus
extern "C" {
#endif
	/****************
	 * STATIC CONTENT *
	 ****************/

	static const ConnectionDataType _JWH_array8type = {.type = ARRAY, .ext.arrayType = UINT8};

	/****************/
	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    init
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_init
	(JNIEnv *env, jobject obj)
	{
		jint ret = WH_init();

		return ret;
	}

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    halt
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_halt
	(JNIEnv *env, jobject obj)
	{
		uint8_t ret = WH_halt();
		jint j = ret;

		return j;
	}

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    recv
	 * Signature: ([B)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_recv
	(JNIEnv *env, jobject obj, jbyteArray data)
	{
		MessageInfo mi;
		jboolean iscopy;
		mi.type = &_JWH_array8type;
		mi.size = (*env)->GetArrayLength(env, data);

		//int8_t* bytes = (*env)->GetByteArrayElements(env, data, &iscopy);
		int8_t *bytes = (*env)->GetPrimitiveArrayCritical(env, data, &iscopy);

		if (iscopy == JNI_TRUE) {
			fprintf(stderr, "msg has been copied!\n");
		}

		if (bytes == NULL) {
			fprintf(stderr, "JVM returned NULL!\n");
			return -1;
		}

		jint ret = WH_recv(bytes, &mi);
		//(*env)->ReleaseByteArrayElements(env,data,bytes,0);
		(*env)->ReleasePrimitiveArrayCritical(env, data, bytes, 0);

		return ret;
	}

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    send
	 * Signature: ([B)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_send
	(JNIEnv *env, jobject obj, jbyteArray data)
	{
		MessageInfo mi;
		jboolean iscopy;
		mi.type = &_JWH_array8type;
		mi.size = (*env)->GetArrayLength(env, data);

		//int8_t* bytes = (*env)->GetByteArrayElements(env, data, &iscopy);
		int8_t *bytes = (*env)->GetPrimitiveArrayCritical(env, data, &iscopy);

		if (iscopy == JNI_TRUE) {
			fprintf(stderr, "msg has been copied!\n");
		}

		if (bytes == NULL) {
			fprintf(stderr, "JVM returned NULL!\n");
			return -1;
		}

		jint ret = WH_send(bytes, &mi);
		//(*env)->ReleaseByteArrayElements(env,data,bytes,JNI_ABORT);
		(*env)->ReleasePrimitiveArrayCritical(env, data, bytes, JNI_ABORT);

		return ret;
	}

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    recv
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_recv__Ljava_lang_String_2
	(JNIEnv *env, jobject obj, jstring data)
	{
		MessageInfo mi;
		jboolean iscopy;
		mi.type = &_JWH_array8type;
		mi.size = (*env)->GetStringLength(env, data) * 2; //TODO change type to the corresponding

		int16_t *bytes = (*env)->GetStringCritical(env, data, &iscopy);

		if (iscopy == JNI_TRUE) {
			fprintf(stderr, "msg has been copied!\n");
		}

		if (bytes == NULL) {
			fprintf(stderr, "JVM returned NULL!\n");
			return -1;
		}

		jint ret = WH_recv(bytes, &mi);
		(*env)->ReleaseStringCritical(env, data, bytes);

		return ret;
	}

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    send
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_send__Ljava_lang_String_2
	(JNIEnv *env, jobject obj, jstring data)
	{
		MessageInfo mi;
		jboolean iscopy;
		mi.type = &_JWH_array8type;
		mi.size = (*env)->GetStringLength(env, data) * 2; //TODO change type to the corresponding

		int16_t *bytes = (*env)->GetStringCritical(env, data, &iscopy);

		if (iscopy == JNI_TRUE) {
			fprintf(stderr, "msg has been copied!\n");
		}

		if (bytes == NULL) {
			fprintf(stderr, "JVM returned NULL!\n");
			return -1;
		}

		jint ret = WH_send(bytes, &mi);
		(*env)->ReleaseStringCritical(env, data, bytes);

		return ret;
	}

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    flushIO
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_es_hpcn_wormhole_Worm_flushIO
	(JNIEnv *env, jobject obj)
	{
		WH_flushIO();
	}

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    getId
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_getId
	(JNIEnv *env, jobject obj)
	{
		uint8_t ret = WH_get_id();
		jint j = ret;

		return j;
	}

#ifdef __cplusplus
}
#endif
#endif
