/* Copyright (c) 2015-2018 Rafael Leira
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_hpcn_wormhole_Worm */

#ifndef _Included_es_hpcn_wormhole_Worm
#define _Included_es_hpcn_wormhole_Worm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_init(JNIEnv *, jobject);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    halt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_halt(JNIEnv *, jobject);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    recv
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_recv___3B(JNIEnv *, jobject, jbyteArray);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    send
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_send___3B(JNIEnv *, jobject, jbyteArray);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    recv
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_recv__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    recv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_hpcn_wormhole_Worm_recv__(JNIEnv *, jobject);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    send
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_send__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    flushIO
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_hpcn_wormhole_Worm_flushIO(JNIEnv *, jobject);

/*
 * Class:     es_hpcn_wormhole_Worm
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_getId(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
