/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_hpcn_wormhole_Worm */

#ifndef _Included_es_hpcn_wormhole_Worm
#define _Included_es_hpcn_wormhole_Worm
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    init
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_init
	(JNIEnv *, jobject);

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    halt
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_halt
	(JNIEnv *, jobject);

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    recv
	 * Signature: ([B)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_recv___3B
	(JNIEnv *, jobject, jbyteArray);

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    send
	 * Signature: ([B)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_send___3B
	(JNIEnv *, jobject, jbyteArray);

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    recv
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_recv__Ljava_lang_String_2
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    send
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_send__Ljava_lang_String_2
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    flushIO
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_es_hpcn_wormhole_Worm_flushIO
	(JNIEnv *, jobject);

	/*
	 * Class:     es_hpcn_wormhole_Worm
	 * Method:    getId
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Worm_getId
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
