/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_hpcn_wormhole_Einstein */

#ifndef _Included_es_hpcn_wormhole_Einstein
#define _Included_es_hpcn_wormhole_Einstein
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     es_hpcn_wormhole_Einstein
	 * Method:    init
	 * Signature: (Ljava/lang/String;Ljava/lang/String;IZ[Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_es_hpcn_wormhole_Einstein_init
	(JNIEnv *, jobject, jstring, jstring, jint, jboolean, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
